# Generated by Django 4.2 on 2026-01-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='user',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gaze_calibrated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gaze_calibration_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
