# Generated by Django 4.2 on 2026-01-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='face_registered',
            new_name='is_face_registered',
        ),
    ]
