# Generated by Django 4.2 on 2026-01-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('trust_score', models.FloatField(default=100.0, help_text='AI-calculated trust score (0-100)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted'), ('FLAGGED', 'Flagged for Review')], default='IN_PROGRESS', max_length=20)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('answers', models.JSONField(default=dict, help_text="Student's answers")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attempts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_attempts',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('FACE_NOT_DETECTED', 'Face Not Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('FACE_MISMATCH', 'Face Mismatch'), ('GAZE_AWAY', 'Looking Away'), ('TAB_SWITCH', 'Tab Switched'), ('FULLSCREEN_EXIT', 'Exited Fullscreen'), ('AUDIO_DETECTED', 'Suspicious Audio'), ('NO_FACE_LONG', 'No Face for Extended Period')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='violations/screenshots/')),
                ('audio_clip', models.FileField(blank=True, null=True, upload_to='violations/audio/')),
                ('metadata', models.JSONField(default=dict, help_text='Additional violation data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='proctoring.examattempt')),
            ],
            options={
                'db_table': 'violations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_detected', models.BooleanField(default=False)),
                ('face_confidence', models.FloatField(default=0.0)),
                ('gaze_on_screen', models.BooleanField(default=False)),
                ('gaze_x', models.FloatField(blank=True, null=True)),
                ('gaze_y', models.FloatField(blank=True, null=True)),
                ('audio_level', models.FloatField(default=0.0)),
                ('speech_detected', models.BooleanField(default=False)),
                ('tab_focused', models.BooleanField(default=True)),
                ('fullscreen_active', models.BooleanField(default=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='proctoring/snapshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='proctoring.examattempt')),
            ],
            options={
                'db_table': 'proctoring_sessions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
