# Generated by Django 4.2 on 2026-02-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_alter_violation_violation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('FACE_NOT_DETECTED', 'Face Not Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('FACE_MISMATCH', 'Face Mismatch'), ('GAZE_DEVIATION', 'Gaze Deviation'), ('TAB_SWITCH', 'Tab Switched'), ('FULLSCREEN_EXIT', 'Exited Fullscreen'), ('AUDIO_DETECTED', 'Suspicious Audio'), ('NO_FACE_LONG', 'No Face for Extended Period'), ('RIGHT_CLICK_BLOCKED', 'Right Click Blocked'), ('F12_BLOCKED', 'F12 Key Blocked'), ('INSPECT_BLOCKED', 'Inspect Element Blocked'), ('CONSOLE_BLOCKED', 'Console Blocked'), ('ELEMENT_PICKER_BLOCKED', 'Element Picker Blocked'), ('VIEW_SOURCE_BLOCKED', 'View Source Blocked'), ('SAVE_PAGE_BLOCKED', 'Save Page Blocked'), ('PRINT_BLOCKED', 'Print Blocked'), ('SCREENSHOT_ATTEMPT', 'Screenshot Attempt'), ('DEVTOOLS_OPEN', 'DevTools Opened'), ('COPY_BLOCKED', 'Copy Blocked'), ('WINDOW_BLUR', 'Window Lost Focus')], max_length=50),
        ),
    ]
