"""
AI Engine Module for Exam Proctoring
Handles face detection, gaze tracking, and audio monitoring
"""

# Version
__version__ = '1.0.0'

# Default configuration values
DEBUG_MODE = True  # ENABLED for request logging
ENABLE_FACE_DETECTION = True
ENABLE_GAZE_TRACKING = True
ENABLE_AUDIO_DETECTION = True
ENABLE_TAB_MONITORING = True
ENABLE_FULLSCREEN_MONITORING = True

# Face Detection Configuration
FACE_DETECTION_CONFIDENCE = 0.5
FACE_RECOGNITION_THRESHOLD = 0.6
MIN_FACE_SIZE = (30, 30)
MAX_FACES_ALLOWED = 1

# Gaze Tracking Configuration
GAZE_DEVIATION_THRESHOLD = 30
GAZE_SAMPLING_RATE = 2
GAZE_SMOOTHING_WINDOW = 5

# Audio Detection Configuration
AUDIO_THRESHOLD = 0.3
SPEECH_CONFIDENCE = 0.7
AUDIO_SAMPLING_RATE = 16000
AUDIO_CHUNK_DURATION = 1.0

# Processing Settings
FRAME_SKIP = 2
BATCH_SIZE = 1
MAX_QUEUE_SIZE = 30

# Violation Thresholds
MAX_GAZE_VIOLATIONS_PER_MINUTE = 10
MAX_AUDIO_VIOLATIONS_PER_MINUTE = 5
MAX_FACE_ABSENCE_SECONDS = 30
MAX_TAB_SWITCHES_PER_MINUTE = 3
MAX_FULLSCREEN_EXITS_PER_MINUTE = 2

# Performance Settings
USE_GPU = True
GPU_MEMORY_FRACTION = 0.3
NUM_THREADS = 4

# Debug Settings
SAVE_DEBUG_FRAMES = False
DEBUG_FRAME_PATH = 'debug_frames/'

# Expose configuration to other modules
__all__ = [
    '__version__',
    'DEBUG_MODE',
    'ENABLE_FACE_DETECTION',
    'ENABLE_GAZE_TRACKING',
    'ENABLE_AUDIO_DETECTION',
    'ENABLE_TAB_MONITORING',
    'ENABLE_FULLSCREEN_MONITORING',
    'FACE_DETECTION_CONFIDENCE',
    'FACE_RECOGNITION_THRESHOLD',
    'MIN_FACE_SIZE',
    'MAX_FACES_ALLOWED',
    'GAZE_DEVIATION_THRESHOLD',
    'GAZE_SAMPLING_RATE',
    'GAZE_SMOOTHING_WINDOW',
    'AUDIO_THRESHOLD',
    'SPEECH_CONFIDENCE',
    'AUDIO_SAMPLING_RATE',
    'AUDIO_CHUNK_DURATION',
    'FRAME_SKIP',
    'BATCH_SIZE',
    'MAX_QUEUE_SIZE',
    'MAX_GAZE_VIOLATIONS_PER_MINUTE',
    'MAX_AUDIO_VIOLATIONS_PER_MINUTE',
    'MAX_FACE_ABSENCE_SECONDS',
    'MAX_TAB_SWITCHES_PER_MINUTE',
    'MAX_FULLSCREEN_EXITS_PER_MINUTE',
    'USE_GPU',
    'GPU_MEMORY_FRACTION',
    'NUM_THREADS',
    'SAVE_DEBUG_FRAMES',
    'DEBUG_FRAME_PATH',
]